from langchain_core.tools import tool
from datetime import datetime
from pathlib import Path
import subprocess
import shutil
import re

@tool
def render_latex_pdf(latex_content: str) -> str:
    """Render a LaTeX document to PDF using Tectonic safely and return the path."""

    if shutil.which("tectonic") is None:
        raise RuntimeError("❌ Tectonic is not installed. Please install it first.")

    try:
        # Step 1: Create output directory
        output_dir = Path("output").absolute()
        output_dir.mkdir(exist_ok=True)

        # Step 2: Generate unique filenames
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        tex_filename = f"paper_{timestamp}.tex"
        pdf_filename = f"paper_{timestamp}.pdf"

        tex_file_path = output_dir / tex_filename
        pdf_file_path = output_dir / pdf_filename

        # Step 3: Sanitize LaTeX content
        sanitized_content = latex_content

        # Remove duplicate preambles and envs
        sanitized_content = re.sub(r"\\documentclass.*?\n", "", sanitized_content)
        sanitized_content = re.sub(r"\\usepackage.*?\n", "", sanitized_content)
        sanitized_content = re.sub(r"\\begin\{document\}", "", sanitized_content)
        sanitized_content = re.sub(r"\\end\{document\}", "", sanitized_content)
        sanitized_content = re.sub(r"\\maketitle", "", sanitized_content)

        # Step 4: Construct full LaTeX file
        preamble = r"""
\documentclass{article}
\usepackage[utf8]{inputenc}
\usepackage{amsmath, amssymb}
\usepackage{hyperref}
\usepackage{graphicx}
\usepackage{geometry}
\geometry{margin=1in}

\title{AI-Generated Research Paper}
\author{Automated Research Agent}
\date{\today}

\begin{document}
\maketitle
"""
        ending = r"""
\end{document}
"""
        full_tex = preamble + sanitized_content + ending

        # Step 5: Write LaTeX to file
        tex_file_path.write_text(full_tex, encoding="utf-8")

        # Step 6: Compile with tectonic
        result = subprocess.run(
            ["tectonic", str(tex_file_path), "--outdir", str(output_dir)],
            cwd=output_dir,
            capture_output=True,
            text=True,
        )

        # Check if compilation succeeded
        if result.returncode != 0:
            print("❌ LaTeX build failed.")
            print(result.stderr)
            raise RuntimeError(f"Tectonic failed:\n{result.stderr}")

        if not pdf_file_path.exists():
            raise FileNotFoundError("❌ PDF file was not generated by Tectonic.")

        print(f"✅ Successfully generated PDF at {pdf_file_path}")

        # ✅ Return a clean file path (for Streamlit button)
        # Optional: include clickable markdown link for chat UI
        pdf_link = f"[📄 Download Generated Paper]({pdf_file_path})"
        return str(pdf_file_path)

    except Exception as e:
        print(f"❌ Error rendering LaTeX: {str(e)}")
        raise
